### ISSUE TITLE
Redirected to reddit.com/r/++++++/ 

### ISSUE THREAD

**Issue by Natedude** [bnkrr/multireddit_export#1]
I am having trouble getting this to work always. Most of the time, when I am on a multi and I press the [ext_url] button, it takes me to a url like this
https://www.reddit.com/r/+++++++++++++++++++++++++++++++++++++++/

How can I fix this?

**Comment by Natedude** [comment]
Found a solution.
Was not working with ViolentMonkey in Brave. Switched to TamperMonkey and it started working.

**Comment by bnkrr** [comment]
Thanks!
Therefore I'll close this issue.
